### ISSUE TITLE
Error when extracting multiple files

### ISSUE THREAD

**Issue by guerkchen** [chamelopi/fls-helper#2]
Tool crashes when extracting multiple files:

`Extracting 157 files, please wait ...'
'Traceback (most recent call last):'
'  File "./fls-helper.py", line 139, in btnextract_click'
'    data.extract_file(self.img_file, fdata.inode, os.path.join(outdir, fdata.name))'
'  File "/root/Dokumente/fls-helper/fls-helper/data.py", line 73, in extract_file'
'    with open(outfile, "wb") as fp:'
'IsADirectoryError: [Errno 21] Ist ein Verzeichnis: '/root/Dokumente/Übung3/A/cache/..'
'Abgebrochen'
`

**Comment by chamelopi** [comment]
Apparently, directory was selected (cannot be extracted)

**Comment by chamelopi** [comment]
Should be fixed.

**Comment by chamelopi** [comment]
Fixed in current version
